BOARD_TAG    = uno
#ARDUINO_PORT = /dev/ttyACM0
#BOARDS_TXT   = /usr/share/arduino/hardware/archlinux-arduino/avr/boards.txt
#ARDUINO_VAR_PATH = /usr/share/arduino/hardware/archlinux-arduino/avr/variants
#ARDUINO_PLATFORM_LIB_PATH = /usr/share/arduino/hardware/archlinux-arduino/avr/libraries 
#ARDUINO_CORE_PATH = /usr/share/arduino/hardware/archlinux-arduino/avr/cores/arduino
ARDMK_VENDOR = archlinux-arduino
include /usr/share/arduino/Arduino.mk
