# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/first.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Robot(object):
    def setupUi(self, Robot):
        Robot.setObjectName("Robot")
        Robot.resize(418, 587)
        self.verticalLayout = QtWidgets.QVBoxLayout(Robot)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.slider_servo_gamma = QtWidgets.QSlider(Robot)
        self.slider_servo_gamma.setMaximum(180)
        self.slider_servo_gamma.setProperty("value", 90)
        self.slider_servo_gamma.setOrientation(QtCore.Qt.Vertical)
        self.slider_servo_gamma.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_servo_gamma.setTickInterval(15)
        self.slider_servo_gamma.setObjectName("slider_servo_gamma")
        self.gridLayout.addWidget(self.slider_servo_gamma, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_servo_alpha = QtWidgets.QLabel(Robot)
        self.label_servo_alpha.setAlignment(QtCore.Qt.AlignCenter)
        self.label_servo_alpha.setObjectName("label_servo_alpha")
        self.gridLayout.addWidget(self.label_servo_alpha, 1, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.slider_servo_theta = QtWidgets.QSlider(Robot)
        self.slider_servo_theta.setMaximum(180)
        self.slider_servo_theta.setProperty("value", 90)
        self.slider_servo_theta.setOrientation(QtCore.Qt.Vertical)
        self.slider_servo_theta.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_servo_theta.setTickInterval(15)
        self.slider_servo_theta.setObjectName("slider_servo_theta")
        self.gridLayout.addWidget(self.slider_servo_theta, 0, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_servo_beta = QtWidgets.QLabel(Robot)
        self.label_servo_beta.setAlignment(QtCore.Qt.AlignCenter)
        self.label_servo_beta.setObjectName("label_servo_beta")
        self.gridLayout.addWidget(self.label_servo_beta, 1, 3, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.slider_servo_beta = QtWidgets.QSlider(Robot)
        self.slider_servo_beta.setMaximum(180)
        self.slider_servo_beta.setProperty("value", 90)
        self.slider_servo_beta.setOrientation(QtCore.Qt.Vertical)
        self.slider_servo_beta.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_servo_beta.setTickInterval(15)
        self.slider_servo_beta.setObjectName("slider_servo_beta")
        self.gridLayout.addWidget(self.slider_servo_beta, 0, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_servo_gamma = QtWidgets.QLabel(Robot)
        self.label_servo_gamma.setAlignment(QtCore.Qt.AlignCenter)
        self.label_servo_gamma.setObjectName("label_servo_gamma")
        self.gridLayout.addWidget(self.label_servo_gamma, 1, 0, 2, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_servo_theta = QtWidgets.QLabel(Robot)
        self.label_servo_theta.setAlignment(QtCore.Qt.AlignCenter)
        self.label_servo_theta.setObjectName("label_servo_theta")
        self.gridLayout.addWidget(self.label_servo_theta, 1, 4, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.slider_servo_alpha = QtWidgets.QSlider(Robot)
        self.slider_servo_alpha.setMaximum(180)
        self.slider_servo_alpha.setProperty("value", 90)
        self.slider_servo_alpha.setOrientation(QtCore.Qt.Vertical)
        self.slider_servo_alpha.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_servo_alpha.setTickInterval(15)
        self.slider_servo_alpha.setObjectName("slider_servo_alpha")
        self.gridLayout.addWidget(self.slider_servo_alpha, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.slider_circle_height = QtWidgets.QSlider(Robot)
        self.slider_circle_height.setMinimum(-50)
        self.slider_circle_height.setMaximum(156)
        self.slider_circle_height.setProperty("value", 50)
        self.slider_circle_height.setOrientation(QtCore.Qt.Vertical)
        self.slider_circle_height.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_circle_height.setTickInterval(15)
        self.slider_circle_height.setObjectName("slider_circle_height")
        self.gridLayout_2.addWidget(self.slider_circle_height, 0, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_circle_gamma = QtWidgets.QLabel(Robot)
        self.label_circle_gamma.setAlignment(QtCore.Qt.AlignCenter)
        self.label_circle_gamma.setObjectName("label_circle_gamma")
        self.gridLayout_2.addWidget(self.label_circle_gamma, 1, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_circle_length = QtWidgets.QLabel(Robot)
        self.label_circle_length.setAlignment(QtCore.Qt.AlignCenter)
        self.label_circle_length.setObjectName("label_circle_length")
        self.gridLayout_2.addWidget(self.label_circle_length, 1, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.slider_circle_length = QtWidgets.QSlider(Robot)
        self.slider_circle_length.setMinimum(-30)
        self.slider_circle_length.setMaximum(156)
        self.slider_circle_length.setProperty("value", 90)
        self.slider_circle_length.setOrientation(QtCore.Qt.Vertical)
        self.slider_circle_length.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_circle_length.setTickInterval(15)
        self.slider_circle_length.setObjectName("slider_circle_length")
        self.gridLayout_2.addWidget(self.slider_circle_length, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_circle_height = QtWidgets.QLabel(Robot)
        self.label_circle_height.setAlignment(QtCore.Qt.AlignCenter)
        self.label_circle_height.setObjectName("label_circle_height")
        self.gridLayout_2.addWidget(self.label_circle_height, 1, 3, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.slider_circle_gamma = QtWidgets.QSlider(Robot)
        self.slider_circle_gamma.setMaximum(180)
        self.slider_circle_gamma.setProperty("value", 90)
        self.slider_circle_gamma.setOrientation(QtCore.Qt.Vertical)
        self.slider_circle_gamma.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_circle_gamma.setTickInterval(15)
        self.slider_circle_gamma.setObjectName("slider_circle_gamma")
        self.gridLayout_2.addWidget(self.slider_circle_gamma, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.slider_cartesian_z = QtWidgets.QSlider(Robot)
        self.slider_cartesian_z.setMinimum(-50)
        self.slider_cartesian_z.setMaximum(100)
        self.slider_cartesian_z.setProperty("value", 50)
        self.slider_cartesian_z.setOrientation(QtCore.Qt.Vertical)
        self.slider_cartesian_z.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_cartesian_z.setTickInterval(15)
        self.slider_cartesian_z.setObjectName("slider_cartesian_z")
        self.gridLayout_3.addWidget(self.slider_cartesian_z, 0, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_cartesian_x = QtWidgets.QLabel(Robot)
        self.label_cartesian_x.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cartesian_x.setObjectName("label_cartesian_x")
        self.gridLayout_3.addWidget(self.label_cartesian_x, 1, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_cartesian_y = QtWidgets.QLabel(Robot)
        self.label_cartesian_y.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cartesian_y.setObjectName("label_cartesian_y")
        self.gridLayout_3.addWidget(self.label_cartesian_y, 1, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.slider_cartesian_y = QtWidgets.QSlider(Robot)
        self.slider_cartesian_y.setMinimum(-100)
        self.slider_cartesian_y.setMaximum(100)
        self.slider_cartesian_y.setProperty("value", 90)
        self.slider_cartesian_y.setOrientation(QtCore.Qt.Vertical)
        self.slider_cartesian_y.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_cartesian_y.setTickInterval(15)
        self.slider_cartesian_y.setObjectName("slider_cartesian_y")
        self.gridLayout_3.addWidget(self.slider_cartesian_y, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_cartesian_z = QtWidgets.QLabel(Robot)
        self.label_cartesian_z.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cartesian_z.setObjectName("label_cartesian_z")
        self.gridLayout_3.addWidget(self.label_cartesian_z, 1, 3, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.slider_cartesian_x = QtWidgets.QSlider(Robot)
        self.slider_cartesian_x.setMinimum(-100)
        self.slider_cartesian_x.setMaximum(100)
        self.slider_cartesian_x.setProperty("value", 90)
        self.slider_cartesian_x.setOrientation(QtCore.Qt.Vertical)
        self.slider_cartesian_x.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_cartesian_x.setTickInterval(15)
        self.slider_cartesian_x.setObjectName("slider_cartesian_x")
        self.gridLayout_3.addWidget(self.slider_cartesian_x, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.buttonBox = QtWidgets.QDialogButtonBox(Robot)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Robot)
        self.buttonBox.accepted.connect(Robot.accept)
        self.buttonBox.rejected.connect(Robot.reject)
        QtCore.QMetaObject.connectSlotsByName(Robot)

    def retranslateUi(self, Robot):
        _translate = QtCore.QCoreApplication.translate
        Robot.setWindowTitle(_translate("Robot", "Robot"))
        self.label_servo_alpha.setText(_translate("Robot", "TextLabel"))
        self.label_servo_beta.setText(_translate("Robot", "TextLabel"))
        self.label_servo_gamma.setText(_translate("Robot", "TextLabel"))
        self.label_servo_theta.setText(_translate("Robot", "TextLabel"))
        self.label_circle_gamma.setText(_translate("Robot", "TextLabel"))
        self.label_circle_length.setText(_translate("Robot", "TextLabel"))
        self.label_circle_height.setText(_translate("Robot", "TextLabel"))
        self.label_cartesian_x.setText(_translate("Robot", "TextLabel"))
        self.label_cartesian_y.setText(_translate("Robot", "TextLabel"))
        self.label_cartesian_z.setText(_translate("Robot", "TextLabel"))

